### ISSUE TITLE
Check all feeds upon starting

### ISSUE THREAD

**Issue by aesedepece** [witnet/data-feeds-explorer#111]
Every time the app restarts, feeds are scheduled to be checked for updates after their configured period.

This makes it quite difficult to check whether a specific price feed is being correctly read from,

It would be really nice to immediately check for updates upon starting the service. That is, adding a `setTimeout` in addition to the `setInterval`.

To avoid overload, a small random delay can be added to each of the different feeds.

**Comment by gabaldon** [comment]
This was fixed in comit: [4258d1ac7f336efdd67d0b41da71d03b7ec0b083](https://github.com/witnet/data-feeds-explorer/commit/4258d1ac7f336efdd67d0b41da71d03b7ec0b083)
