### ISSUE TITLE
Data Feeds Explorer redesign

### ISSUE THREAD

**Issue by gabaldon** [witnet/data-feeds-explorer#112]
Redesign website to have a better UX.

- [ ] Create Witnet Data Feeds Explorer logo
- [x] Implement design for filtering feeds
- [x] Implement design for the main view

**Comment by gabaldon** [comment]
https://www.figma.com/file/cGAYe6HJJfW8LZbzIFhsRb/Untitled?node-id=0%3A1

**Comment by Tommytrg** [comment]
> https://www.figma.com/file/cGAYe6HJJfW8LZbzIFhsRb/Untitled?node-id=0%3A1

The redesign can be found here
