### ISSUE TITLE
Responsive sidebar disappear when resizing to a greater width

### ISSUE THREAD

**Issue by Tommytrg** [witnet/data-feeds-explorer#140]
If the sidebar is open ( width < 850px) and we resize the window to be greater than 850px, the window will show a blank state. The expected behavior is to close the responsive sidebar instead of just hiding it. 

![image](https://user-images.githubusercontent.com/24905681/157266972-1253590f-59cf-48b0-a10d-5f21dbcd4f56.png)
![image](https://user-images.githubusercontent.com/24905681/157267788-79e65112-b191-418c-a657-5f587748dd22.png)

**Comment by gabaldon** [comment]
This was fixed in commit: [0481ad8054ee6882b02515516e07130382d210be](https://github.com/witnet/data-feeds-explorer/commit/0481ad8054ee6882b02515516e07130382d210be)
