### ISSUE TITLE
Discuss what should be shown in the front page 

### ISSUE THREAD

**Issue by gabaldon** [witnet/data-feeds-explorer#152]
Discuss how the landing page will look like to avoid redirecting to Ethereum price feeds directly.

**Comment by Tommytrg** [comment]
### Goals

- Decide what to show as a main page for the data feeds explorer. Currently, we are redirecting to the Ethereum price feeds.

### Conclusion

In the main view we have to implement:

- A list of all the different chains. Every chain should show how many feeds have.
- A section with the upcoming chain integrations
- A section with users and partners
- A section with the total number of data feeds, networks and chains.
- When we have a newsletter, a section to subscribe to the newsletter.
- Update the footer to add socials and link to the different ecosystem websites
