### ISSUE TITLE
Retrieve logos from a static server

### ISSUE THREAD

**Issue by gabaldon** [witnet/data-feeds-explorer#153]

**Comment by Tommytrg** [comment]
To accomplish our goal of avoiding release a new version, every time we add or update a new price feed, we have to implement `#153`, but we also have to add images without releasing a new version. Currently, when we add a new price feed, we include the network and token SVGs in the release.

A workaround would be to upload the images to a static server and fetch the images from there. The easiest way to build this is setting up an [Amazon S3](https://aws.amazon.com/s3/), [Azure Blob Storage](https://azure.microsoft.com/en-us/services/storage/blobs/), [Google Cloud Storage](https://cloud.google.com/storage) or [Firebase Storage](https://firebase.google.com/docs/storage)

See also #154

**Comment by Tommytrg** [comment]
Finally, we have decided to upload the different logos to the Github repository and read them from there
