### ISSUE TITLE
Fix performance error 

### ISSUE THREAD

**Issue by gabaldon** [witnet/data-feeds-explorer#164]
The data feeds explorer API shows a timeout in retrieving the address of the contract. The console shows the following error:

`Error reading contracts state: Error: Error reading contract state Error: Invalid JSON RPC response: "<!DOCTYPE html>\n\n\n\n <html class=\"no-js\" lang=\"en-US\"> \n<head>\n<title>Temporarily unavailable | api.avax-test.network | Cloudflare</title></title>\n<meta charset=\"UTF-8\" />\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/cf.errors.css\" type=\"text/css\" media=\"screen,projection\" />\n\n<style type=\"text/css\">body{margin:0;padding:0}</style>\n\n\n\n<script>\n  if (!navigator.cookieEnabled) {\n    window.addEventListener('DOMContentLoaded', function () {\n      var cookieEl = document.getElementById('cookie-alert');\n      cookieEl.style.display = 'block';\n    })\n  }\n</script>\n\n\n\n</head>\n<body>\n  <div id=\"cf-wrapper\">\n    <div class=\"cf-alert cf-alert-error cf-cookie-error\" id=\"cookie-alert\" data-translate=\"enable_cookies\">Please enable cookies.</div>\n    <div id=\"cf-error-details\" class=\"cf-error-details-wrapper\">\n      <div class=\"cf-wrapper cf-header cf-error-overview\">\n        <h1>\n          <span class=\"cf-error-type\" data-translate=\"error\">Error</span>\n          <span class=\"cf-error-code\">1105</span>\n          <small class=\"heading-ray-id\">Ray ID: 6f2e4ef06ba46b38 &bull; 2022-03-28 08:09:04 UTC</small>\n        </h1>\n        <h2 class=\"cf-subheadline\" data-translate=\"error_desc\">Temporarily unavailable</h2>\n      </div>\n\n      <section></section>\n\n      <div class=\"cf-section cf-wrapper\">\n        <div class=\"cf-columns two\">\n          <div class=\"cf-column\">\n            <h2 data-translate=\"what_happened\">What happened?</h2>\n            <p>You've requested a page on a website (api.avax-test.network) that is on the <a data-orig-proto=\"https\" data-orig-ref=\"www.cloudflare.com/5xx-error-landing/\" target=\"_blank\">Cloudflare</a> network. The page could not be rendered due to a temporary fault.</p>\n          </div>\n\n          \n        </div>\n      </div>\n\n      <div class=\"cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300\">\n  <p class=\"text-13\">\n    <span class=\"cf-footer-item sm:block sm:mb-1\">Cloudflare Ray ID: <strong class=\"font-semibold\">6f2e4ef06ba46b38</strong></span>\n    <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n    <span class=\"cf-footer-item sm:block sm:mb-1\"><span>Your IP</span>: 52.166.178.145</span>\n    <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n    <span class=\"cf-footer-item sm:block sm:mb-1\"><span>Performance &amp; security by</span> <a rel=\"noopener noreferrer\" href=\"https://www.cloudflare.com/5xx-error-landing\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n    \n  </p>\n</div>\n\n\n    </div>\n  </div>\n\n  <script type=\"text/javascript\">\n  window._cf_translation = {};\n  \n  \n</script>\n\n</body>\n</html>\n\n"
    at Web3Middleware.<anonymous> (/usr/src/app/dist/web3Middleware/index.js:267:31)
    at step (/usr/src/app/dist/web3Middleware/index.js:44:23)
    at Object.throw (/usr/src/app/dist/web3Middleware/index.js:25:53)
    at rejected (/usr/src/app/dist/web3Middleware/index.js:17:65)`

There was also an error related to the query made by the Data Feeds bot. We weren´t able to reproduce the issue in a local environment.

**Comment by Tommytrg** [comment]
Closed #168
