### ISSUE TITLE
Add RSS feed of all feeds, with all the available information

### ISSUE THREAD

**Issue by aesedepece** [witnet/data-feeds-explorer#211]
Should the API serve an RSS feed of all price feeds in chronological order of addition, we'd be able to set up a quick IFTTT or Zapier workflow that will send a tweet from our Twitter account every time we add support for a new price feed, or even every time a significant delay is detected, without having to add any fancy logic for that in our backend.

**Comment by gabaldon** [comment]
This was implemented in commit: [c60c1c156f8fbbdb7ce4c0afdde9f56a314938b0](https://github.com/witnet/data-feeds-explorer/commit/c60c1c156f8fbbdb7ce4c0afdde9f56a314938b0)
