### ISSUE TITLE
Add Etherscan link to price feed data

### ISSUE THREAD

**Issue by mariocao** [witnet/data-feeds-explorer#23]
It would be nice to have the etherscan link of the data feed price data, so that the user could check the Ethereum transaction in which the data point was reported.

**Comment by tmpolaczyk** [comment]
You can use the `events` API to get a list of all the `completeUpdate` events. This includes the resulting price and the ethereum transaction hash:

https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#contract-events
