### ISSUE TITLE
Create a cron job that triggers a backup

### ISSUE THREAD

**Issue by Tommytrg** [witnet/data-feeds-explorer#320]
Create a service in one of the AWS instances we have deployed to run a cron job that triggers a `mongodump` backup.

**Comment by aesedepece** [comment]
TBD: rotation policy

**Comment by Tommytrg** [comment]
We are running a cron job that executes a `mongodump` command every midnight. Also, we are deleting backups older than 10 days

**Comment by Tommytrg** [comment]
The backups are being triggered by the cron job
