### ISSUE TITLE
Adopt latest WitnetPriceFeeds ABI

### ISSUE THREAD

**Issue by guidiaz** [witnet/data-feeds-explorer#349]
Instead of relying on WitnetPriceRouter + WitnetPriceFeed, as to:

- [ ] Reduce drastically number of Web3 calls (one single web3 call per chain for updating prices)
- [ ] Enable new UI/UX features
- [ ] Avoid having to deploy/mantain WitnetPriceRouter and bypassed (old) WitnetPriceFeed instances

**Comment by Tommytrg** [comment]
This is already implemented
