### ISSUE TITLE
Migrate to Nuxt3

### ISSUE THREAD

**Issue by gabaldon** [witnet/data-feeds-explorer#370]
- [x] Use graphql queries instead of apollo
- [x] Update `LanguageSwitcher`
- [x] Update dark mode theme to use tailwind classes
- [x] Add pinia
- [x] Update linter
- [x] Add vitest
- [x] Update components script to use setup
- [x] dynamic SEO
- [x] Update lightweight-charts

**Comment by Tommytrg** [comment]
[tag 2.0](https://github.com/witnet/data-feeds-explorer/releases/tag/v2.0.0) is using nuxt3
