### ISSUE TITLE
Fix naming in new testnets

### ISSUE THREAD

**Issue by gabaldon** [witnet/data-feeds-explorer#404]
Fix errors in new testnet networks:

**Conflux Core Testnet:**

- [ ] Wrong naming `conflux-core.testnet`

- [ ] Pricefeed address not set for `conflux-core-testnet_cfx-usdt_6`

**Conflux e-Space Testnet:** 

- [ ] Wrong naming `conflux-espace.testnet`

**OKX X1:** 

- [ ] Wrong naming `sepoliaokx-x1.sepolia`

**OKT Chain Testnet:** 

- [ ] Wrong naming `okx-oktchain.testnet`

**Comment by Tommytrg** [comment]
Closed by #407
