### ISSUE TITLE
[api] Implement automatic update of supported price feeds

### ISSUE THREAD

**Issue by gabaldon** [witnet/data-feeds-explorer#415]
The DFE does not currently support updating supported price feeds list when new array of supported price feeds is received from the contract.
`listenWitnetPriceFeeds` method only updates resultRequests

**Comment by Tommytrg** [comment]
After some debugging, we detected that the problem is related to deleted price feeds from the contract. With the current implementation, the DFE can detect if a new price feed is added but will detect a removed price feed as delayed.

**Comment by Tommytrg** [comment]
close by #421
