### ISSUE TITLE
Update tally form

### ISSUE THREAD

**Issue by gabaldon** [witnet/data-feeds-explorer#419]
Current form: https://tally.so/r/mOP09R

- Would it be useful to differentiate between testnet and mainnet?

It is necessary to define new flows to get other type of data or support:

- Other type of feed
- General support request

**Comment by Tommytrg** [comment]
This issue is blocked until @gabaldon can give us access to the tally account

**Comment by gabaldon** [comment]
https://tally.so/r/mOP09R
