### ISSUE TITLE
CFX/USDT price feed value is shown with incorrect decimal digits 

### ISSUE THREAD

**Issue by aesedepece** [witnet/data-feeds-explorer#73]
CFX/USDT price feed value is shown with incorrect decimal digits.

![image](https://user-images.githubusercontent.com/1316439/131811974-b58ad87d-5f29-45d1-8f23-87b15853bf80.png)

This feed uses 6 decimal digits, so the right value above should be 0.302221

**Comment by gabaldon** [comment]
fixed in https://feeds.witnet.io/
<img width="277" alt="Screenshot 2021-11-29 at 12 11 31" src="https://user-images.githubusercontent.com/16032491/143857909-4e150093-1e98-4f96-bd94-0562dd6689bb.png">
