### ISSUE TITLE
Add Feeds for CELO/USD, CELO/EUR

### ISSUE THREAD

**Issue by gabaldon** [witnet/data-feeds-explorer#97]

**Comment by guidiaz** [comment]
First implementation attempt deployed to **Celo Alfajores**:
- CeloEurPriceFeed: `0x9627CB0314368BC70587912119a4F03Ba0b179B5`
- CeloUsdPriceFeed: `0xA4dBe748BA8E3220eAC07cB4c951909fc089c3dD`

**Comment by guidiaz** [comment]
Deployed also to Celo Mainnet:
- CeloEurPriceFeed: 0xdDBf8eBC2C5435bf2251611466b45bf625a6E1DB
- CeloUsdPriceFeed: 0x45EE6664E3be238C3ebC0462e0750e103ff6F24E
